#!/usr/bin/env python3
import os
import re
import time
import urllib.parse
import urllib.request

REPO = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(REPO, "raw")
GETTING_REAL = "https://basecamp.com/gettingreal"
WIKIPEDIA_SUMMARY = "https://en.wikipedia.org/api/rest_v1/page/summary/"

ESSAYS = {
    "pg-do-things-that-dont-scale.html": "https://paulgraham.com/ds.html",
    "pg-how-to-get-startup-ideas.html": "https://paulgraham.com/startupideas.html",
    "pg-startup-equals-growth.html": "https://paulgraham.com/growth.html",
    "pg-be-relentlessly-resourceful.html": "https://paulgraham.com/relres.html",
    "pg-how-to-make-wealth.html": "https://paulgraham.com/wealth.html",
    "pg-schlep-blindness.html": "https://paulgraham.com/schlep.html",
    "pg-startup-mistakes.html": "https://paulgraham.com/startupmistakes.html",
    "pg-users.html": "https://paulgraham.com/newideas.html",
    "saas-starter-stack.md": "https://raw.githubusercontent.com/timb-103/saas-starter-stack/main/README.md",
    "open-saas.md": "https://raw.githubusercontent.com/wasp-lang/open-saas/main/README.md",
    "getting-real.html": GETTING_REAL,
}

HEALTH = {
    "nimh-adhd.html": "https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd",
    "nimh-depression.html": "https://www.nimh.nih.gov/health/topics/depression",
    "nimh-anxiety-disorders.html": "https://www.nimh.nih.gov/health/topics/anxiety-disorders",
    "nimh-bipolar-disorder.html": "https://www.nimh.nih.gov/health/topics/bipolar-disorder",
    "nimh-psychotherapies.html": "https://www.nimh.nih.gov/health/topics/psychotherapies",
    "nimh-caring-for-your-mental-health.html": "https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health",
    "nimh-do-i-need-help.html": "https://www.nimh.nih.gov/health/publications/my-mental-health-do-i-need-help",
    "nimh-stress.html": "https://www.nimh.nih.gov/health/publications/stress",
    "nimh-find-help.html": "https://www.nimh.nih.gov/health/find-help",
    "nhlbi-sleep-deprivation.html": "https://www.nhlbi.nih.gov/health/sleep-deprivation",
}

WIKIPEDIA = [
    "Flow_(psychology)",
    "Zeigarnik_effect",
    "Spacing_effect",
    "Testing_effect",
    "Implementation_intention",
    "Yerkes–Dodson_law",
    "Cognitive_load",
    "Attention_restoration_theory",
    "Attentional_control",
    "Human_multitasking",
    "Behavioral_activation",
    "Procrastination",
    "Habit",
    "Self-determination_theory",
    "Self-efficacy",
    "Goal_setting",
    "Decision_fatigue",
    "Planning_fallacy",
    "Sunk_cost",
    "Dunning–Kruger_effect",
    "Incubation_(psychology)",
    "Learned_helplessness",
    "Perfectionism_(psychology)",
    "Rumination_(psychology)",
    "Mindfulness",
    "Cognitive_restructuring",
    "Cognitive_behavioral_therapy",
    "Occupational_burnout",
    "Attention_deficit_hyperactivity_disorder",
    "Major_depressive_disorder",
    "Anxiety_disorder",
    "Bipolar_disorder",
    "Insomnia",
    "Sleep_hygiene",
    "Circadian_rhythm",
    "Sleep_deprivation",
    "Psychiatry",
    "Psychoeducation",
    "Mental_health",
    "Psychology",
    "Cognitive_psychology",
    "Social_psychology",
    "Behavioral_economics",
    "Cognitive_science",
    "Neuroscience",
    "Positive_psychology",
    "Cognitive_bias",
    "Executive_functions",
    "Attention",
    "Motivation",
    "Working_memory",
    "Hofstadter's_law",
    "Student_syndrome",
    "Law_of_triviality",
    "Goodhart's_law",
    "Overjustification_effect",
    "Grit_(personality_trait)",
    "Conscientiousness",
    "Locus_of_control",
    "Self-control",
    "Delayed_gratification",
    "Ego_depletion",
    "Confirmation_bias",
    "Anchoring_effect",
    "Availability_heuristic",
    "Loss_aversion",
    "Status_quo_bias",
    "Present_bias",
    "Optimism_bias",
    "Illusion_of_control",
    "Overchoice",
    "Analysis_paralysis",
    "Impostor_syndrome",
    "Chunking_(psychology)",
    "Forgetting_curve",
    "Desirable_difficulty",
    "Metacognition",
    "Reinforcement",
    "Task_switching_(psychology)",
    "Mind-wandering",
    "Social_loafing",
    "Social_facilitation",
    "Hawthorne_effect",
    "Pygmalion_effect",
    "Peak–end_rule",
    "Hedonic_treadmill",
    "Negativity_bias",
    "Fundamental_attribution_error",
    "Self-serving_bias",
    "Overconfidence_effect",
    "Curse_of_knowledge",
    "Hindsight_bias",
    "Survivorship_bias",
    "Escalation_of_commitment",
    "Endowment_effect",
    "IKEA_effect",
    "Not_invented_here",
    "Cognitive_dissonance",
    "Framing_effect_(psychology)",
    "Information_overload",
    "Satisficing",
    "Psychological_stress",
    "Coping",
    "Psychological_resilience",
    "Self-compassion",
    "Broaden-and-build",
    "Job_crafting",
    "Work–life_balance",
    "Workaholic",
    "Occupational_stress",
    "Loneliness",
    "Social_support",
    "Sleep_inertia",
    "Power_nap",
    "Chronotype",
    "Ultradian_rhythm",
    "Post-lunch_dip",
    "Directed_attention_fatigue",
    "Boreout",
    "Divergent_thinking",
    "Functional_fixedness",
    "Fear_of_missing_out",
    "Social_comparison_theory",
    "Self-handicapping",
    "Defensive_pessimism",
    "Learned_optimism",
    "Hyperfocus",
    "Timeboxing",
    "Pomodoro_Technique",
    "Attention_span",
    "Attention_economy",
    "Nudge_theory",
    "Commitment_device",
    "Writing_therapy",
    "Presenteeism",
    "Mental_disorder",
    "Psychopathology",
    "Psychopharmacology",
    "Psychiatrist",
    "Clinical_psychology",
    "Mental_health_professional",
    "Psychotherapy",
    "Psychiatric_medication",
    "Mood_disorder",
    "Diagnostic_and_Statistical_Manual_of_Mental_Disorders",
    "ICD-11",
    "Comorbidity",
    "Generalized_anxiety_disorder",
    "Panic_disorder",
    "Panic_attack",
    "Social_anxiety_disorder",
    "Obsessive–compulsive_disorder",
    "Post-traumatic_stress_disorder",
    "Adjustment_disorder",
    "Persistent_depressive_disorder",
    "Seasonal_affective_disorder",
    "Cyclothymia",
    "Hypomania",
    "Mania",
    "Anhedonia",
    "Apathy",
    "Suicidal_ideation",
    "Suicide_prevention",
    "Crisis_hotline",
    "Self-harm",
    "Substance_use_disorder",
    "Alcohol_use_disorder",
    "Caffeine_dependence",
    "Cannabis_use_disorder",
    "Internet_addiction_disorder",
    "Video_game_addiction",
    "Problematic_smartphone_use",
    "Delayed_sleep_phase_disorder",
    "Circadian_rhythm_sleep_disorder",
    "Sleep_disorder",
    "Hypersomnia",
    "Sleep_apnea",
    "Chronic_stress",
    "Acute_stress_reaction",
    "Emotional_exhaustion",
    "Depersonalization-derealization_disorder",
    "Adult_attention_deficit_hyperactivity_disorder",
    "Attention_deficit_hyperactivity_disorder_management",
    "Methylphenidate",
    "Autism_spectrum",
    "Antidepressant",
    "Selective_serotonin_reuptake_inhibitor",
    "Anxiolytic",
    "Benzodiazepine_dependence",
    "Mood_stabilizer",
    "Lithium_(medication)",
    "Interpersonal_psychotherapy",
    "Acceptance_and_commitment_therapy",
    "Dialectical_behavior_therapy",
    "Mindfulness-based_cognitive_therapy",
    "Mindfulness-based_stress_reduction",
    "Exposure_therapy",
    "Cognitive_behavioral_therapy_for_insomnia",
    "Behaviour_therapy",
    "Online_counseling",
    "Telepsychiatry",
    "Psychiatric_assessment",
    "Relapse_prevention",
    "Treatment-resistant_depression",
    "Light_therapy",
    "Melatonin_as_a_medication_and_supplement",
    "Sleep_debt",
    "Microsleep",
    "Shift_work_sleep_disorder",
    "Anger_management",
    "Social_isolation",
    "Mental_health_first_aid",
    "Peer_support",
    "Self-help_groups_for_mental_health",
    "Emotional_dysregulation",
    "Somatic_symptom_disorder",
    "Atypical_depression",
    "Psychological_trauma",
    "Complex_post-traumatic_stress_disorder",
    "Psychosis",
    "Caffeine-induced_anxiety_disorder",
    "Sleep_medicine",
    "Prolonged_grief_disorder",
    "Dissociation_(psychology)",
    "Recovery_approach",
    "Executive_dysfunction",
    "Neurodiversity",
    "Alexithymia",
    "Depression_(mood)",
    "Cognitive_distortion",
    "Worry",
    "Wake_therapy",
    "Software_as_a_service",
    "Startup_company",
    "Product/market_fit",
    "Minimum_viable_product",
    "Customer_development",
    "Churn_rate",
    "Lean_startup",
    "Subscription_business_model",
    "Customer_lifetime_value",
    "Customer_acquisition_cost",
    "Freemium",
    "Entrepreneurship",
]


def slugify(title):
    return re.sub(r"[^a-z0-9]+", "-", urllib.parse.unquote(title).lower()).strip("-")


def download(url, path):
    if os.path.exists(path) and os.path.getsize(path) > 0:
        return False
    request = urllib.request.Request(url, headers={"User-Agent": "LockIn/1.0 (https://github.com/adipascu/menubar-timer)"})
    with urllib.request.urlopen(request, timeout=45) as response:
        open(path, "wb").write(response.read())
    time.sleep(0.5)
    return True


def main():
    os.makedirs(os.path.join(RAW, "gettingreal"), exist_ok=True)
    os.makedirs(os.path.join(RAW, "wikipedia"), exist_ok=True)
    for name, url in {**ESSAYS, **HEALTH}.items():
        download(url, os.path.join(RAW, name))

    index = open(os.path.join(RAW, "getting-real.html"), encoding="utf-8", errors="ignore").read()
    chapters = sorted(set(re.findall(r'href="(/gettingreal/[^"]+)"', index)))
    for path in chapters:
        download(f"https://basecamp.com{path}", os.path.join(RAW, "gettingreal", path.split("/")[-1] + ".html"))

    for title in WIKIPEDIA:
        url = WIKIPEDIA_SUMMARY + urllib.parse.quote(title, safe="")
        download(url, os.path.join(RAW, "wikipedia", slugify(title) + ".json"))

    print(
        f"{len(ESSAYS)} essays, {len(chapters)} Getting Real chapters, "
        f"{len(HEALTH)} NIH pages and {len(WIKIPEDIA)} Wikipedia summaries in {RAW}"
    )


if __name__ == "__main__":
    main()
